 const data = {
  subjects: [
    'Een hart onder de riem steken',
    'Topper',
    'NAME, Je bent geweldig',
    'Alleen maar liefde',
    'Held',
    'Nu even dit',
    'Omdat je het verdient',
  ],
  greetings: [
    'Beste NAME,',
    'Lieve NAME',
    'NAME,',
    'Geachte NAME,',
  ],
  senderNames: [
    'Nadia',
    'Henk',
    'Wietse',
    'Truus',
    'Kees',
    'Myrthe',
    'Julia',
    'Piet',
    'Lisanne',
    'Wouter',
    'Gait',
  ],
  introductions: [
    'Ik ben SENDERNAME en zou normaal nooit zoiets sturen.',
    'Mijn naam is SENDERNAME en niet eens fan van jou.',
    'Mijn naam is SENDERNAME en ik ben niet eens fan van jou.',
    'SENDERNAME hier.',
    'Ik ben SENDERNAME en ik kom uit Zuid-Limburg.',
    'Altijd zou ik je blijven aanmoedigen. Je kunt het.'
  ],
  randomSentences: [
    'Ik moet je dit sturen.',
    'Er wordt een hetze tegen jou gevoerd.',
    'Het is genoeg!',
    'We moeten samen voor ons land opkomen.',
    'Dit is typisch de MSM.',
    'Ik wil je graag een hart onder de riem steken.',
    'Dit is alleen om de echte problemen te verdoezelen.',
    '5G!',
    'Stiekem zou ik willen dat ik jou was.',
    'Ze willen niet zien hoe goed je bent.',
    'Ze zijn jaloers.',
    'Ze kunnen niet in je schaduw staan.',
    'Je bent te goed voor ons.',
    'Ik zie wél wie je bent.',
    'Laat ze de echte problemen aanpakken.',
    'Het is tijd dat dit gezegd wordt.',
    'Jij hebt het beste met ons voor.',
    'Het is gewoon gemeen.',
    'Het wordt op de man gespeeld.',
    'Je kunt niet eens meer een grapje maken tegenwoordig.',
  ],
  finishingSentences: [
    'Laat je niet kisten!',
    'Keep up the good work!',
    'Hou vol!',
    'Je staat er niet alleen voor!',
    'Blijf sterk!',
    'Ik sta achter je!',
    'Bedankt voor alles!',
  ],
  endings: [
    'Met vriendelijke groet,',
    'Zorg goed voor jezelf,',
    'Met liefde,',
    'Kus,',
    'Dikke doei,',
  ],
}

export default data;