 const data = {
  subjects: [
    'Een hart onder de riem steken',
    'Topper',
    'NAME, Je bent geweldig',
    'Alleen maar liefde',
    'Held',
    'Nu even dit',
    'Omdat je het verdient',
    'Een beetje liefde',
    'NAME, je kunt het.',
    'BAAS',
    'WE VERTROUWEN JE!',
    'Juist nu.',
  ],
  greetings: [
    'Beste NAME,',
    'Lieve NAME,',
    'NAME,',
    'Geachte NAME,',
    'Heuj NAME,',
    'Allergeweldigste NAME,',
    'Geweldige NAME,',
    'Goede NAME,',
    'Allerbeste NAME,',
  ],
  senderNames: [
    'Nadia',
    'Henk',
    'Wietse',
    'Truus',
    'Kees',
    'Myrthe',
    'Julia',
    'Piet',
    'Lisanne',
    'Wouter',
    'Gait',
  ],
  introductions: [
    'Ik ben SENDERNAME en zou normaal nooit zoiets sturen.',
    'Mijn naam is SENDERNAME en ik ben niet eens fan van jou.',
    'Mijn naam is SENDERNAME en steun jou en je partij volledig!',
    'SENDERNAME hier.',
    // 'Ik ben SENDERNAME en ik kom uit Zuid-Limburg.',
    'Altijd zou ik je blijven aanmoedigen. Je kunt het.',
    'Ik, SENDERNAME, ben niet bij je weg te slaan.',
    'Je doet het echt geweldig.',
    'In één woord wauw.',
    'Na de aantijgingen aan uw adres over totaal verwaarloosbare uitspraken die u gedaan zou hebben weet ik het zeker.',
  ],
  randomSentences: [
    'Ik moet je dit sturen.',
    'Er wordt een hetze tegen jou gevoerd.',
    'Het is genoeg!',
    'We moeten samen voor ons land opkomen.',
    'Dit is typisch de MSM.',
    'Ik wil je graag een hart onder de riem steken.',
    'Dit is alleen om de echte problemen te verdoezelen.',
    '5G!',
    'DE MEDIA!!!!',
    'Stiekem zou ik willen dat ik jou was.',
    'Ze willen niet zien hoe goed je bent.',
    'Ze zijn jaloers.',
    'Ze kunnen niet in je schaduw staan.',
    'Je bent te goed voor ons.',
    'Ik zie wél wie je bent.',
    'Laat ze de echte problemen aanpakken.',
    'Het is tijd dat dit gezegd wordt.',
    'Jij hebt het beste met ons voor.',
    'Het is gewoon gemeen.',
    'Het wordt op de man gespeeld.',
    'Je kunt niet eens meer een grapje maken tegenwoordig.',
    '\nHelemaal goed.',
    '\nBlijf sterk!\n',
  ],
  finishingSentences: [
    'Laat je niet kisten!',
    'Keep up the good work!',
    'Hou vol!',
    'Je staat er niet alleen voor!',
    'Blijf sterk!',
    'Ik sta achter je!',
    'Bedankt voor alles!',
  ],
  endings: [
    'Met vriendelijke groet,',
    'Zorg goed voor jezelf,',
    'Met liefde,',
    'Kus,',
    'Dikke doei,',
  ],
}

// const data = {
//   subjects: [
//     'Een hart onder de riem steken',
//     'Topper',
//     'Aantijgingen',
//   ],
//   greetings: [
//     'Geachte heer NAME,',
//     'Kerel.',
//     'Beste Thierry,',
//   ],
//   senderNames: [
//     'Nadia',
//   ],
//   introductions: [
//     'Je doet het echt geweldig.',
//     'Na de aantijgingen aan uw adres over totaal verwaarloosbare uitspraken die u gedaan zou hebben weet ik het zeker.',
//     'Mijn naam is SENDERNAME, ik ben moslima, hoofddoekdragende en Marokkaanse en steun jou en je partij volledig!',
//   ],
//   randomSentences: [
//     'Ik ga op 17 maart mijn stem uitbrengen op u!',
//     'De heksenjacht van de media op u en uw partij is nu echt begonnen, en dit alleen omdat ze weten dat u goed gaat scoren op 17 maart.',
//     '\nMaar ik en vele anderen met mij zullen niet buigen voor de media, Thierry!',
//     'Ik wil je graag een hart onder de riem steken, omdat de media het op je hebben gemunt',
//     'Hoge bomen vangen veel wind',
//     'Iedereen die dit spel van de media doorhebben, weet ook dat dit weer een mediastunt is omdat ze weten dat je super veel succes zoal boeken de aankomende verkiezingen.',
//     'Ik en vele anderen zullen je ondanks al deze onzinnige en negatieve berichtgeving gewoon steunen!',
//     'Je staat er niet alleen voor.',
//     'Blijf sterk!',
//     'Nederland heeft het fvd hard nodig.',
//     'Sinds Annabel en Joost enz. vertrokken zijn ben je wat mij betreft een topper.',
//     'Helemaal goed.\n',
//     'Wat ik vanavond op tv zag hoe je reageerde op de journalisten die weer eens Prive mailtjes bekend aan het maken waren om FVD zwart te maken',
//     '\n\nPerfecte reactie.\n\n',
//     'Mijn stem op 17 Maart had je al maar nu ben ik absoluut voor de volle 100% overtuigd dat ik op jou ga stemmen.',
//     'Helemaal goed.'
//   ],
//   finishingSentences: [
//     'Keep up the good work!',
//     'Het allerbeste toegewenst.',
//   ],
//   endings: [
//     'Met vriendelijke groet,',
//     'Zorg goed voor jezelf',
//   ],
// }

// const data = {
//  subjects: [
//    'Een hart onder de riem steken',
//    'Topper',
//    'Aantijgingen',
//  ],
//  greetings: [
//    'Geachte heer NAME,',
//    'Kerel.',
//    'Beste NAME,',
//  ],
//  senderNames: [
//    'Nadia',
//  ],
//  introductions: [
//    // 'Je doet het echt geweldig.',
//    // 'Na de aantijgingen aan uw adres over totaal verwaarloosbare uitspraken die u gedaan zou hebben weet ik het zeker.',
//    // 'Mijn naam is SENDERNAME, ik ben moslima, hoofddoekdragende en Marokkaanse en steun jou en je partij volledig!',
//  ],
//  randomSentences: [
//    'Na de aantijgingen aan uw adres over totaal verwaarloosbare uitspraken die u gedaan zou hebben weet ik het zeker.',
//      'Ik ga op 17 mart mijn stem uitbrengen op u!',
//      'De heksenjacht van de media op u en uw partij is nu echt begonnen, en dit alleen omdat ze weten dat u goed gaat scoren op 17 maart.',
//      'Maar ik en vele anderen met mij zullen niet buigen voor de media, NAME!',
//      'Mijn naam is Nadia, ik ben moslima, hoofddoekdragende en Marokkaanse en steun jou en je partij volledig!',
//      'Ik wil je graag een hart onder de riem steken, omdat de media het op je hebben gemunt.',
//      'Hoge bomen vangen veel wind.',
//      'Iedereen die dit spel van de media doorhebben, weet ook dat dit weer een mediastunt is omdat ze weten dat je super veel succes zal boeken de aankomende verkiezingen.',
//      'Ik en vele anderen zullen je ondanks al deze onzinnige en negatieve berichtgeving gewoon steunen!',
//      'Je staat er niet alleen voor!',
//      'Blijf sterk!',
//      'Nederland heeft NAME hard nodig.',
//      'Je doet het echt geweldig.',
//      'Sinds Annabel en Joost enz. vertrokken zijn ben je wat mij betreft een topper.',
//      'Helemaal goed.',
//      'Wat ik vanavond op tv zag je reageerde op de journalisten die weer eens Prive mailtjes bekend aan het maken waren om NAME zwart te maken.',
//      'Perfecte reactie.',
//      'Mijn stem op 17 Maart had je al maar nu ben ik absoluut voor de volle 100% overtuigd dat ik op jou ga stemmen.',
//      'Helemaal goed.',
//      'Ga zo door kerel.',
//      'En laat je niet kisten.',
//  ],
//  finishingSentences: [
//    'Keep up the good work!',
//    'Het allerbeste toegewenst.',
//  ],
//  endings: [
//    'Met vriendelijke groet,',
//    'Zorg goed voor jezelf',
//  ],
// }

export default data;
